In [1]:
import numpy as np

In [2]:
a = np.array([np.nan for _ in range(5)])
a

array([ nan,  nan,  nan,  nan,  nan])

In [3]:
a.sum()

nan

In [4]:
a.nansum()

AttributeError: 'numpy.ndarray' object has no attribute 'nansum'

In [5]:
a.mean()

nan

In [6]:
a.nanmean()

AttributeError: 'numpy.ndarray' object has no attribute 'nanmean'

In [7]:
np.nanmean(a)

/home/jep/anaconda3/envs/jupy/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: Mean of empty slice
  if __name__ == '__main__':


nan

In [8]:
np.nansum(a)

0.0

In [9]:
b = a.copy()
b[1] = 15.
b[3] = 5.
b is a, a, b

(False,
 array([ nan,  nan,  nan,  nan,  nan]),
 array([ nan,  15.,  nan,   5.,  nan]))

In [10]:
np.nanmean(b), np.nansum(b)

(10.0, 20.0)