In [1]:
import numpy as np

In [2]:
a = np.array([0, 0, 0, 1])
a

array([0, 0, 0, 1])

In [3]:
a.sum()


1

In [4]:
a.mean()

0.25

In [5]:
b = np.array([0, 0, np.nan, 1])
b

array([  0.,   0.,  nan,   1.])

In [6]:
b.sum()

nan

In [7]:
b.mean()

nan

In [8]:
def sum_(x):
    return sum(y for y in x if not np.isnan(y))

In [9]:
sum_(a)

1

In [10]:
sum_(b)

1.0

In [11]:
def mean_(x):
    return np.array(list(y for y in x if not np.isnan(y))).mean()

In [12]:
mean_(a)

0.25

In [13]:
mean_(b)

0.33333333333333331

In [14]:
1. + np.nan

nan

In [15]:
1. + 2. + 3.

6.0

In [16]:
1. is np.nan


False

In [17]:
np.nan is np.nan

True

In [18]:
b[2]

nan

In [19]:
b[2] is np.nan

False

In [20]:
nan

NameError: name 'nan' is not defined

In [21]:
np.isnan(1.)

False

In [22]:
np.isnan(np.nan)

True

In [23]:
np.isnan(b[2])

True

In [24]:
np.isnotnan(1.)

AttributeError: module 'numpy' has no attribute 'isnotnan'

In [25]:
c = np.array([0, 0, None, 1])
c

array([0, 0, None, 1], dtype=object)

In [26]:
c.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [27]:
c.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [28]:
d = np.array([0, 0, np.nan, 'np.nan', 1])
d

array(['0', '0', 'nan', 'np.nan', '1'], 
      dtype='<U32')

In [29]:
for x in d:
    try:
        is_nan = np.isnan(x)
    except TypeError:
        is_nan = 'mu'
    print(type(x), is_nan, x)

<class 'numpy.str_'> mu 0
<class 'numpy.str_'> mu 0
<class 'numpy.str_'> mu nan
<class 'numpy.str_'> mu np.nan
<class 'numpy.str_'> mu 1


In [30]:
d = np.array([0, 0, np.nan, 1])
d

array([  0.,   0.,  nan,   1.])

In [31]:
for x in d:
    try:
        is_nan = np.isnan(x)
    except TypeError:
        is_nan = 'mu'
    print(type(x), is_nan, x)

<class 'numpy.float64'> False 0.0
<class 'numpy.float64'> False 0.0
<class 'numpy.float64'> True nan
<class 'numpy.float64'> False 1.0
